// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"time"

	"github.com/99designs/gqlgen/graphql"
)

type Category struct {
	ID   string `json:"ID"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

type NewPost struct {
	Image      *graphql.Upload `json:"image"`
	Title      string          `json:"title"`
	Summary    string          `json:"summary"`
	Link       string          `json:"link"`
	CategoryID string          `json:"categoryID"`
}

type Post struct {
	ID       string    `json:"id"`
	ImageURL string    `json:"imageURL"`
	Title    string    `json:"title"`
	Summary  string    `json:"summary"`
	Link     string    `json:"link"`
	Category *Category `json:"category"`
	PostedOn time.Time `json:"postedOn"`
}
